### ISSUE TITLE
Could you add support for shaka-player

### ISSUE THREAD

**Issue by raestrada95** [cdnbye/dashjs-p2p-engine#2]
Could you add support for shaka-engine?

Some similar companies support the shaka player engine,it would be very useful because the chromecast which is based on shaka is widely used .

**Comment by snowinszu** [comment]
OK

**Comment by snowinszu** [comment]
Hello, raestrada95.  We had add support for shaka-player!

**Comment by raestrada95** [comment]
Hi great news, I'm going to try it thx
