### ISSUE TITLE
Peers Behind Multiple Levels of NAT

### ISSUE THREAD

**Issue by raestrada95** [cdnbye/dashjs-p2p-engine#3]
Hi, I'm having trouble running the p2p network in installations with double nat as in the example image.

![WhatsApp Image 2020-02-28 at 2 35 24 AM](https://user-images.githubusercontent.com/34411704/75524423-77bbf680-59d3-11ea-8adc-dbe393c0dc96.jpeg)

It is common in some ISPs in my region not give public IP to each user due to depletion of IPv4 by lacnic. I would like to know if anyone has any suggestions that allow me to work the p2p network in these circumstances

Image description.
> In some topologies involving multiple NAT devices, two clients cannot establish an “optimal” P2P route between them without specific knowledge of the topology. Consider a final scenario, depicted in Figure 6. Suppose NAT $C$ is a large industrial NAT deployed by an internet service provider (ISP) to multiplex many customers onto a few public IP addresses, and NATs $A$ and $B$ are small consumer NAT routers deployed independently by two of the ISP's customers to multiplex their private home networks onto their respective ISP-provided IP addresses. Only server $S$ and NAT $C$ have globally routable IP addresses; the “public” IP addresses used by NAT $A$ and NAT $B$ are actually private to the ISP's address realm, while client $A$'s and $B$'s addresses in turn are private to the addressing realms of NAT $A$ and NAT $B$, respectively. Each client initiates an outgoing connection to server $S$ as before, causing NATs $A$ and $B$ each to create a single public/private translation, and causing NAT $C$ to establish a public/private translation for each session.``

**Comment by snowinszu** [comment]
Hello, WebRTC using ICE to handle p2p establishment.

**Comment by raestrada95** [comment]
Thanks for the answer, could you give me an example of configuration?
